### PR TITLE
first draft of database

### PR DESCRIPTION
**Pull request by walterrdcpalma**

### CODE REVIEW

**Comment by botclimber** [comment]
Why for the database model all tables have IDs ? cant we just define some key fields as the primary keys ?

**Comment by walterrdcpalma** [comment]
> Why for the database model all tables have IDs ? cant we just define some key fields as the primary keys ?

WE could, but for example, if you use the email as primary key instead of int, it means that the in every table that you need to reference that key, you will use email (varchar) which uses more memory and it is slower if reaches a bigger scale than int, normally we use composite keys (which can be other that id) in intermediate table for many to many relations, besides that imo is better this way

**Comment by botclimber** [comment]
revPK
for example in this case we can avoid creating a id column to define a primaryKey

**Comment by walterrdcpalma** [comment]
> revPK for example in this case we can avoid creating a id column to define a primaryKey

In that case could make sense, yes

**Comment by botclimber** [comment]
We can use this approach for now (IDs in all tables), and discuss it later.

**Pull request merged**
